name: chatus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cloudinary_url_gen: ^1.8.0
  cloudinary_flutter: ^1.3.0
  supabase_flutter: ^2.10.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  provider:
  timeago:
  lottie:
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/